### ISSUE TITLE
Add Jupyter Notebook in R for Creating and Submitting Datasets

### ISSUE THREAD

**Issue by mburrus** [ess-dive/essdive-package-service-examples#27]
**Describe the Feature Request**

Add a new Jupyter Notebook that demonstrates how to create JSON-LD and submit datasets to ESS-DIVE with the API in R.

- [ ] Verify it can be run in Binder

**Comment by emilyarobles** [comment]
@mburrus RStudio [can run on binder](https://github.com/binder-examples/r), so I'm putting together the R tutorial for creating and submitting datasets as an R markdown file since this will likely be more familiar to those who work in R. If we want a Jupyter notebook R version as well I'm happy to put that together.

**Comment by mburrus** [comment]
Completed sometime in 2023: https://github.com/ess-dive/essdive-tutorials/blob/main/Tutorial_DataSubmission_R.Rmd
